### ISSUE TITLE
suggestion: maybe install `run-clang-tidy` via `cargo binstall`?

### ISSUE THREAD

**Issue by AucaCoyan** [lmapii/run-clang-tidy#29]
Hi! I really like this project.
I was surprised when I found out `clang tidy` and `clang-format` doesn't format folders recursively 😢.

I was wondering if you are interested in the possibility to install the app via `cargo binstall`. It's a shorcut that skips the compilation, via downloading the binary github releases.
To make this possible it's necesarry to add some fields in `Cargo.toml`. Nothing very deep in the building.

Thanks!

**Comment by AucaCoyan** [comment]
Oh, wait. Actually even without the cargo.toml properties you can `cargo binstall run-clang-format` and install the binary directly.
I wonder what's the benefit of the toml fields 🤔

**Comment by lmapii** [comment]
I found the following in the documentation:

> Binstall works by fetching the crate information from crates.io and searching the linked repository for matching releases and artifacts

Since the repository on `crates.io` points to this GitHub repository it seems to be able to fetch the latest release.

Regarding recursive formatting and tidy - `clang-tidy` and `clang-format` will always need to be called for files or you'll need some IDE integration (e.g., `vscode` calling `clang-format` on save for you). Otherwise, these wrappers should be able to recursively search the provided tree. What exactly are you struggling with?

**Comment by AucaCoyan** [comment]
> Binstall works by fetching the crate information from crates.io and searching the linked repository for matching releases and artifacts

Thanks! This issue then is not necessary / resolved 😄 . I have no blockers, all good!
Thank you for the app, it's a saver!
